import speech_recognition as sr
import vlc
import gpiozero
from time import sleep
from gpiozero import LED
from gpiozero import Button
from signal import pause

button = Button(26)

BlueIeksejie = LED(22)
RedIeksejie = LED(27)
GreenIeksejie = LED(17)

BlueArejie = LED(18)
GreenArejie = LED(23)
RedArejie = LED(24)

motors3 = LED(20)
motors2 = LED(21)
motors4 = LED(16)
motors1 = LED(12)

motors1.off()
motors2.off()
motors3.off()
motors4.off()

RedArejie.off()
GreenArejie.off()
BlueArejie.off()

RedIeksejie.off()
GreenIeksejie.off()
BlueIeksejie.off()

GreenIeksejie.on()
GreenArejie.on()
sleep(1)
print("Starting code ...")
GreenIeksejie.off()
GreenArejie.off()
sleep(1)
print("Press the button to start!")

while True:
    if button.is_pressed:
        print("Button was pushed!")
        media = vlc.MediaPlayer("question.mp3")
        media.play()
        print("What do you whant to drink?")
        sleep(6)
        RedIeksejie.on()
        RedArejie.on()
        BlueArejie.on()
        listener = sr.Recognizer()

        with sr.Microphone() as source:
            voice = listener.listen(source)
            command = listener. recognize_google(voice)
            print("You choose: "+command)

            if command == "Fanta":
                media = vlc.MediaPlayer("Fanta.mp3")
                media.play()
                
                sleep(8)
                   
                listener = sr.Recognizer()
                
                with sr.Microphone() as source:
                    voice = listener.listen(source)
                    command = listener. recognize_google(voice)
                    print("You want "+command+" size drink.")
                    RedIeksejie.off()
                    RedArejie.off()
                    BlueArejie.off()

                    if command == "small":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose small.")
                        motors1.on()
                        sleep(4.18)
                        motors1.off()
                        motors1.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "medium":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose medium.")
                        motors1.on()
                        sleep(9.49)
                        motors1.off()
                        motors1.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "large":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose large.")
                        motors1.on()
                        sleep(14.48)
                        motors1.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()
                        
            if command == "Sprite":
                media = vlc.MediaPlayer("Sprite.mp3")
                media.play()
                
                sleep(8)
                
                listener = sr.Recognizer()
                
                with sr.Microphone() as source:
                    voice = listener.listen(source)
                    command = listener. recognize_google(voice)
                    print("You want "+command+" size drink.")
                    RedIeksejie.off()
                    RedArejie.off()
                    BlueArejie.off()

                    if command == "small":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose small.")
                        motors2.on()
                        sleep(4.18)
                        motors2.off()
                        motors2.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "medium":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose medium.")
                        motors2.on()
                        sleep(9.49)
                        motors2.off()
                        motors2.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "large":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose large.")
                        motors2.on()
                        sleep(14.48)
                        motors2.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

            if command == "enjoy":
                media = vlc.MediaPlayer("Enjoy.mp3")
                media.play()
                
                sleep(7)
                   
                listener = sr.Recognizer()
                
                with sr.Microphone() as source:
                    voice = listener.listen(source)
                    command = listener. recognize_google(voice)
                    print("You want "+command+" size drink.")
                    RedIeksejie.off()
                    RedArejie.off()
                    BlueArejie.off()

                    if command == "small":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose small.")
                        motors3.on()
                        sleep(4.18)
                        motors3.off()
                        motors3.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "medium":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose medium.")
                        motors3.on()
                        sleep(9.49)
                        motors3.off()
                        motors3.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "large":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose large.")
                        motors3.on()
                        sleep(14.48)
                        motors3.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()
            if command == "Coca-Cola":
                media = vlc.MediaPlayer("Coca-Cola.mp3")
                media.play()
                
                sleep(8)
                   
                listener = sr.Recognizer()
                
                with sr.Microphone() as source:
                    voice = listener.listen(source)
                    command = listener. recognize_google(voice)
                    print("You want "+command+" size drink.")
                    RedIeksejie.off()
                    RedArejie.off()
                    BlueArejie.off()

                    if command == "small":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose small.")
                        motors4.on()
                        sleep(4.18)
                        motors4.off()
                        motors4.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "medium":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose medium.")
                        motors4.on()
                        sleep(9.49)
                        motors4.off()
                        motors4.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

                    if command == "large":
                        RedArejie.on()
                        GreenArejie.on()
                        RedIeksejie.on()
                        GreenIeksejie.on()
                        print("You choose large.")
                        motors4.on()
                        sleep(14.44)
                        motors4.off()
                        RedArejie.off()
                        GreenArejie.off()
                        RedIeksejie.off()
                        GreenIeksejie.off()
                        GreenIeksejie.on()
                        GreenArejie.on()
                        sleep(10)
                        GreenIeksejie.off()
                        GreenArejie.off()

